apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: logging
  namespace: openshift-logging
spec:
  inputs:
    - audit:
        sources:
          - auditd
          - ovn
      name: audit
      type: audit
    - infrastructure:
        sources:
          - container
          - node
      name: infra
      type: infrastructure
    - application: {}
      name: app
      type: application
  managementState: Managed
  outputs:
    - lokiStack:
        authentication:
          token:
            from: serviceAccount
        target:
          name: lokistack-logging
          namespace: openshift-logging
        tls:
          ca:
            configMapName: openshift-service-ca.crt
            key: service-ca.crt
          clientKey:
            secretName: lokistack-logging-gateway-client-http
            key: tls.key
          clientCert:
            secretName: lokistack-logging-gateway-client-http
            key: tls.crt
      name: loki
      type: lokiStack
  pipelines:
    - inputRefs:
        - audit
        - infra
        - app
      name: all-to-loki
      outputRefs:
        - loki
  serviceAccount:
    name: logcollector
