# serviceaccount 與 role logging-collector-write-logs binding

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: binding-logging-collector-write-logs
subjects:
  - kind: ServiceAccount
    name: logcollector
    namespace: openshift-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logging-collector-logs-writer
