## role collect-application-logs openshift-logging operator 會幫你建立
# serviceaccount 與 role collect-application-logs binding


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binding-collect-application-logs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collect-application-logs
subjects:
  - kind: ServiceAccount
    name: logcollector
    namespace: openshift-logging
